### ISSUE TITLE
css: change cursor to a click pointer when hovering something click-able 

### ISSUE THREAD

**Issue by Felicious** [Felicious/Boba-Bill-2#30]
In the display of multiple transactions, the `[+]` indicates that pressing this will expand the box, displaying the details of that transaction. However, it's not made clear because the mouse doesn't change into the `select` hand icon that makes it obvious that the [+] is clickable. Therefore,

**Expected behavior**: mouse cursor changes to the pointer hand icon upon hovering over "[+]" in `Transaction`

**Comment by Felicious** [comment]
In your code, use "button" class name to indicate something is a clickable element.

example:
```html
<p class="something button"> click meee </p>
```

In Stylesheet.css`:
```css
.button {
  cursor: pointer;
}
.button:hover {
  text-decoration: underline;
}
```
