### ISSUE TITLE
bug: apply pink underline to active component only

### ISSUE THREAD

**Issue by Felicious** [Felicious/Boba-Bill-2#44]
https://github.com/Felicious/Boba-Bill-2/blob/5d7830ebd807cef1125419a6c62ea43bcdd61fc8/App.vue#L63

Expected behavior: apply pink underline ('tab-front') to the active component only; other components get gray underline

What's happening: all underlines are pink.

![image](https://user-images.githubusercontent.com/23611711/115103220-0a379600-9f05-11eb-9110-93557bc709ac.png)

Observation: `computed` method `computedLine()` is applying the pink color to all lines.

**Comment by Felicious** [comment]
Stylesheet.css:
```css
/* styling for the tab button */
.tab-front {
  position: relative;
  margin: 0 0 1rem 0;
  display: flex;
  justify-content: center;
  height: 1.75rem;
  width: 120%;
  /*picked a random light gray */
  border-bottom: 5px none;
}
```

```html
<template>
<button
      v-for="(tab, index) in tabs"
      :key="index"
      class="tab"
      :class="['tab-button', { active: tab === activeTab }, 'toggleLine']"
      @click="activeTab = tab"
    >
      <span class="tab-front" :style="{ 'border-bottom': computedLine }">{{
        tab
      }}</span>
</template>

<script>
export default {
  components: {
    FriendList,
    TransactionList,
    CalculateList
  },

  computed: {
computedLine() {
      console.log("does this do anything??");
      console.log(this.lineColor);
      return this.lineColor;
    }
  },

  data() {
return {
lineColor: "5px solid #f09381"
};
}
</script>
